version: "3.8"

services:
  cert-fetcher:
    image: alpine:latest
    container_name: cert-fetcher
    entrypoint: >
      sh -c "
      apk add --no-cache openssh &&
      mkdir -p /certificates &&
      ssh-keyscan -H $DB_EC2_HOST >> /etc/ssh/ssh_known_hosts &&
      scp -i /root/db_key.pem $DB_EC2_USER@$DB_EC2_HOST:/etc/ssl/mongodb/ca.crt /certificates/ca.crt &&
      scp -i /root/db_key.pem $DB_EC2_USER@$DB_EC2_HOST:/etc/ssl/mongodb/server.pem /certificates/server.pem &&
      sleep infinity
      "
    environment:
      DB_EC2_HOST: ${DB_EC2_HOST:-default-db-host}
      DB_EC2_USER: ${DB_EC2_USER:-default-db-user}
    volumes:
      - cert-vol:/certificates
      - ./db_key.pem:/root/db_key.pem:ro
    networks:
      - backend-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: starteryou-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
      FRONTEND_URL: http://54.196.202.145:8080
      VITE_BACKEND_URL: http://54.196.202.145:3000
      MONGO_TLS: "true"
      MONGO_TLS_CA: /certificates/ca.crt
      MONGO_TLS_CERT: /certificates/server.pem
    volumes:
      - cert-vol:/certificates:ro
      - ./backend:/usr/src/app
      - ./backend/uploads:/usr/src/app/uploads
    ports:
      - "3000:3000"
    networks:
      - backend-network
    depends_on:
      - cert-fetcher
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: starteryou-frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      BACKEND_URL: http://54.196.202.145:3000
    depends_on:
      - backend
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  cert-vol:
