version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: starteryou-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - FRONTEND_URL=http://54.196.202.145:8080
      - VITE_BACKEND_URL=http://54.196.202.145:3000
      - PORT=3000
    env_file:
      - .env  # Ensures the env file is passed into the container
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - ./keys:/usr/src/app/keys
      - /usr/src/app/node_modules
    networks:
      - starteryou-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - tunnel

  tunnel:
    image: alpine:latest
    container_name: ssh-tunnel
    command: >
      sh -c "apk add --no-cache openssh &&
             chmod 600 /keys/myKey.pem &&
             mkdir -p ~/.ssh &&
             ssh-keyscan 52.207.194.195 >> ~/.ssh/known_hosts &&
             ssh -N -L 27017:localhost:27017 ec2-user@52.207.194.195 -i /keys/myKey.pem"
    restart: always
    networks:
      - starteryou-network
    volumes:
      - ./keys:/keys
      - /etc/ssl/mongodb:/etc/ssl/mongodb:ro,z

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: starteryou-frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URL=http://54.196.202.145:3000
    depends_on:
      - backend
    networks:
      - starteryou-network

networks:
  starteryou-network:
    driver: bridge
