services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: starteryou-backend
    restart: unless-stopped
    env_file:
      - .env  # Use the root .env file
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - starteryou-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: starteryou-frontend
    restart: unless-stopped
    ports:
      - "8080:80"  # Assuming you're using Nginx
    env_file:
      - .env  # Use the root .env file
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}  # Reference from .env file
    depends_on:
      - backend
    networks:
      - starteryou-network

networks:
  starteryou-network:
    driver: bridge