services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: starteryou-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
      FRONTEND_URL: http://54.196.202.145:8080
      VITE_BACKEND_URL: http://54.196.202.145:3000
      MONGO_TLS: "true"
      MONGO_TLS_CA: /run/secrets/mongo_tls_ca
      MONGO_TLS_CERT: /run/secrets/mongo_tls_cert
    secrets:
      - mongo_tls_ca
      - mongo_tls_cert
    volumes:
      - ./backend:/usr/src/app
      - ./backend/uploads:/usr/src/app/uploads
    ports:
      - "3000:3000"
    networks:
      - backend-network
    depends_on:
      sshtunnel:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
