version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: starteryou-backend
    restart: unless-stopped
    
    # Multiple environment loading methods
    env_file:
      - .env
    
    environment:
      # Core environment configuration
      - NODE_ENV=production
      - PORT=3000
      
      # Frontend-related URLs
      - FRONTEND_URL=http://54.196.202.145:8080
      - VITE_BACKEND_URL=http://54.196.202.145:3000
      
      # MongoDB Configuration with fallback to .env
      - MONGO_USER=${MONGO_USER:-${MONGO_USER}}
      - MONGO_PASSWORD=${MONGO_PASSWORD:-${MONGO_PASSWORD}}
      - MONGO_HOST=${MONGO_HOST:-${MONGO_HOST}}
      - MONGO_PORT=${MONGO_PORT:-${MONGO_PORT}}
      - MONGO_DB=${MONGO_DB:-${MONGO_DB}}
      - MONGO_AUTH_SOURCE=${MONGO_AUTH_SOURCE:-${MONGO_AUTH_SOURCE}}
      - MONGO_TLS=${MONGO_TLS:-${MONGO_TLS}}
      - MONGO_TLS_CA=${MONGO_TLS_CA:-${MONGO_TLS_CA}}
      - MONGO_TLS_CERT=${MONGO_TLS_CERT:-${MONGO_TLS_CERT}}
      - MONGO_APP_NAME= ${MONGO_APP_NAME:-${MONGO_APP_NAME }}

    
    # Enhanced volume mappings
    volumes:
      # Bind mount the entire backend directory
      - ./backend:/usr/src/app
      
      # Mount SSL keys and certificates
      - ./keys:/usr/src/app/keys
      
      # Persistent node_modules
      - /usr/src/app/node_modules
      
      # Explicitly mount .env file
      - ./.env:/usr/src/app/.env
      
      # Mount SSL certificates
      - /etc/ssl/mongodb:/etc/ssl/mongodb:ro
      
      # Uploads volume
      - ./backend/uploads:/usr/src/app/uploads
    
    ports:
      - "3000:3000"
    
    networks:
      - starteryou-network
    
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    depends_on:
      - tunnel
    
    # Optional healthcheck
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  tunnel:
    image: alpine:latest
    container_name: ssh-tunnel
    command: >
      sh -c "apk add --no-cache openssh &&
             chmod 600 /keys/myKey.pem &&
             mkdir -p ~/.ssh &&
             ssh-keyscan 52.207.194.195 >> ~/.ssh/known_hosts &&
             ssh -N -L 27017:localhost:27017 ec2-user@52.207.194.195 -i /keys/myKey.pem"
    restart: always
    networks:
      - starteryou-network
    volumes:
      - ./keys:/keys
      - /etc/ssl/mongodb:/etc/ssl/mongodb:ro,z

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: starteryou-frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URL=http://54.196.202.145:3000
    depends_on:
      - backend
    networks:
      - starteryou-network

networks:
  starteryou-network:
    driver: bridge
