name: Deploy to AWS EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Export Secrets to Environment
      - name: Export secrets
        run: |
          echo "DB_EC2_HOST=${{ secrets.DB_EC2_HOST }}" >> $GITHUB_ENV
          echo "DB_EC2_USER=${{ secrets.DB_EC2_USER }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
          echo "MONGO_USER=${{ secrets.MONGO_USER }}" >> $GITHUB_ENV
          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> $GITHUB_ENV
          echo "MONGO_DB=${{ secrets.MONGO_DB }}" >> $GITHUB_ENV
          echo "MONGO_AUTH_SOURCE=${{ secrets.MONGO_AUTH_SOURCE }}" >> $GITHUB_ENV
          echo "MONGO_APP_NAME=${{ secrets.MONGO_APP_NAME }}" >> $GITHUB_ENV

      # Step 3: Decode SSH Key
      - name: Decode SSH Key
        run: |
          echo "${{ secrets.DB_EC2_SSH_KEY_B64 }}" | base64 --decode > ~/.ssh/db_key.pem
          chmod 600 ~/.ssh/db_key.pem

      # Step 4: Set Up SSH Tunnel
      - name: Set up SSH Tunnel
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          ssh-keyscan -H "${DB_EC2_HOST}" >> ~/.ssh/known_hosts
          ssh -N -L 27017:localhost:27017 ${DB_EC2_USER}@${DB_EC2_HOST} -i ~/.ssh/db_key.pem &

      # Step 5: Verify SSH Tunnel
      - name: Verify SSH Tunnel
        run: |
          if nc -z localhost 27017; then
            echo "SSH Tunnel Verified!"
          else
            echo "Failed to verify SSH Tunnel."
            exit 1
          fi

      # Step 6: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.DB_EC2_SSH_KEY }}
          script: |
            echo "Running deployment script..."
            # Your deployment script here
