name: Deploy to AWS EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set Up SSH Tunnel
      - name: Set up SSH Tunnel
        run: |
          echo "Setting up SSH tunnel..."
          # Ensure the .ssh directory exists
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Add the database server to known hosts
          ssh-keyscan -H "${{ secrets.DB_EC2_HOST }}" >> ~/.ssh/known_hosts

          # Save the private key for SSH
          echo "${{ secrets.DB_EC2_SSH_KEY }}" > ~/.ssh/db_key.pem
          chmod 600 ~/.ssh/db_key.pem

          # Start SSH tunnel in the background
          ssh -N -L 27017:localhost:27017 ${{ secrets.DB_EC2_USER }}@${{ secrets.DB_EC2_HOST }} -i ~/.ssh/db_key.pem &
          echo "SSH tunnel started."

      # Step 3: Verify SSH Tunnel
      - name: Verify SSH Tunnel
        run: |
          echo "Verifying SSH tunnel..."
          if nc -z localhost 27017; then
            echo "SSH Tunnel Verified!"
          else
            echo "Failed to verify SSH Tunnel."
            exit 1
          fi

      # Step 4: Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 5: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            #!/bin/bash
            set -e
            set -o pipefail

            log() { echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*"; }
            handle_error() { log "Error occurred on line $1"; exit 1; }
            trap 'handle_error $LINENO' ERR

            PROJECT_ROOT="/home/ec2-user/Starteryou-Website"
            REPO_DIR="${PROJECT_ROOT}/Starteryou"
            ENV_FILE="${REPO_DIR}/.env"

            log "Ensuring project root exists..."
            mkdir -p "$PROJECT_ROOT"
            cd "$PROJECT_ROOT"

            log "Managing repository..."
            if [ ! -d "$REPO_DIR" ]; then
              log "Cloning repository..."
              git clone https://github.com/starteryouInc/Starteryou-Website.git -b develop Starteryou
            else
              log "Pulling latest changes..."
              cd "$REPO_DIR"
              git fetch origin develop
              git reset --hard origin/develop
            fi

            log "Creating .env file..."
            rm -f "$ENV_FILE"
            touch "$ENV_FILE"
            chmod 600 "$ENV_FILE"

            cat > "$ENV_FILE" << EOF
            NODE_ENV=production
            MONGO_USER=${{ secrets.MONGO_USER }}
            MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}
            MONGO_HOST=localhost # Access via SSH tunnel
            MONGO_PORT=27017
            MONGO_DB=${{ secrets.MONGO_DB }}
            MONGO_AUTH_SOURCE=${{ secrets.MONGO_AUTH_SOURCE }}
            MONGO_TLS=true
            MONGO_TLS_CA=/etc/ssl/mongodb/ca.crt
            MONGO_TLS_CERT=/etc/ssl/mongodb/server.pem
            MONGO_APP_NAME=${{ secrets.MONGO_APP_NAME }}
            EOF

            log "Restarting Docker..."
            sudo systemctl start docker || sudo systemctl restart docker

            log "Cleaning up old Docker resources..."
            docker-compose down --volumes --remove-orphans
            docker system prune -af --volumes

            log "Building and starting Docker containers..."
            docker-compose up -d --build

            log "Verifying containers..."
            docker ps

            log "Deployment completed successfully!"
