name: Deploy to AWS EC2
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download SSL Certificates from Database Server
        env:
          DB_EC2_SSH_KEY: ${{ secrets.DB_EC2_SSH_KEY }}
          DB_EC2_USER: ${{ secrets.DB_EC2_USER }}
          DB_EC2_HOST: ${{ secrets.DB_EC2_HOST }}
        run: |
          # Prepare SSH
          mkdir -p ~/.ssh
          echo "$DB_EC2_SSH_KEY" > ~/.ssh/db_server_key
          chmod 600 ~/.ssh/db_server_key
          ssh-keyscan -H $DB_EC2_HOST >> ~/.ssh/known_hosts

          # Create local directory for SSL certificates
          mkdir -p ./keys/mongodb-ssl

          # Archive and Download SSL Certificates
          ssh -i ~/.ssh/db_server_key $DB_EC2_USER@$DB_EC2_HOST "sudo tar -czf /tmp/mongodb-ssl.tar.gz -C /etc/ssl mongodb"
          scp -i ~/.ssh/db_server_key $DB_EC2_USER@$DB_EC2_HOST:/tmp/mongodb-ssl.tar.gz ./keys/mongodb-ssl/
          tar -xzf ./keys/mongodb-ssl/mongodb-ssl.tar.gz -C ./keys/mongodb-ssl/

          # Verify SSL Files
          echo "Listing SSL certificates:"
          ls -l ./keys/mongodb-ssl/mongodb/

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            #!/bin/bash
            set -e
            set -o pipefail

            log() { echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*"; }
            handle_error() { log "Error occurred on line $1"; exit 1; }
            trap 'handle_error $LINENO' ERR

            PROJECT_ROOT="/home/ec2-user/Starteryou-Website"
            REPO_DIR="${PROJECT_ROOT}/Starteryou"
            ENV_FILE="${REPO_DIR}/.env"

            log "Ensuring project root exists..."
            mkdir -p "$PROJECT_ROOT"
            cd "$PROJECT_ROOT"

            log "Managing repository..."
            if [ ! -d "$REPO_DIR" ]; then
              log "Cloning repository..."
              git clone https://github.com/starteryouInc/Starteryou-Website.git -b develop Starteryou
            else
              log "Pulling latest changes..."
              cd "$REPO_DIR"
              git fetch origin develop
              git reset --hard origin/develop
            fi

            log "Copying SSL certificates..."
            mkdir -p "$REPO_DIR/keys/mongodb-ssl"
            cp -r ./keys/mongodb-ssl/* "$REPO_DIR/keys/mongodb-ssl/"
            chmod 644 "$REPO_DIR/keys/mongodb-ssl/"*

            log "Creating .env file..."
            rm -f "$ENV_FILE"
            touch "$ENV_FILE"
            chmod 600 "$ENV_FILE"

            cat > "$ENV_FILE" << EOF
            NODE_ENV=production
            MONGO_USER=${{ secrets.MONGO_USER }}
            MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}
            MONGO_HOST=${{ secrets.MONGO_HOST }}
            MONGO_PORT=${{ secrets.MONGO_PORT }}
            MONGO_DB=${{ secrets.MONGO_DB }}
            MONGO_AUTH_SOURCE=${{ secrets.MONGO_AUTH_SOURCE }}
            MONGO_TLS=${{ secrets.MONGO_TLS }}
            MONGO_TLS_CA=${{ secrets.MONGO_TLS_CA }}
            MONGO_TLS_CERT=${{ secrets.MONGO_TLS_CERT }}
            MONGO_APP_NAME=${{ secrets.MONGO_APP_NAME }}
            EOF

            log "Restarting Docker..."
            sudo systemctl start docker || sudo systemctl restart docker

            log "Cleaning up old Docker resources..."
            docker-compose down --volumes --remove-orphans
            docker system prune -af --volumes

            log "Building and starting Docker containers..."
            docker-compose up -d --build

            log "Verifying containers..."
            docker ps

            log "Deployment completed successfully!"
