name: Deploy to AWS EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Verify SSH Tunnel to Database
      - name: Verify SSH Tunnel to Database
        run: |
          # Ensure the .ssh directory exists
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Add the database server to known hosts
          ssh-keyscan -H "${{ secrets.DB_EC2_HOST }}" >> ~/.ssh/known_hosts

          # Save the private key for SSH
          echo "${{ secrets.DB_EC2_SSH_KEY }}" > ~/.ssh/db_key.pem
          chmod 600 ~/.ssh/db_key.pem

          # Verify the SSH tunnel to the database server
          ssh -i ~/.ssh/db_key.pem ${{ secrets.DB_EC2_USER }}@${{ secrets.DB_EC2_HOST }} "echo 'Database Server SSH Verified!'"

      # Step 3: Deploy Application to EC2
      - name: Deploy Application to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            #!/bin/bash
            set -e

            # Define the log function
            log() {
              echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*"
            }

            # Ensure Git is installed
            log "Ensuring Git is installed..."
            if ! command -v git &> /dev/null; then
              sudo yum update -y || sudo apt-get update -y
              sudo yum install -y git || sudo apt-get install -y git
            fi

            # Set project and repository directories
            PROJECT_ROOT="/home/ec2-user/Starteryou-Website"
            REPO_DIR="${PROJECT_ROOT}/Starteryou"
            ENV_FILE="${REPO_DIR}/.env"

            # Navigate to project directory or clone if it doesn't exist
            if [ ! -d "$REPO_DIR" ]; then
              log "Cloning repository..."
              mkdir -p "$PROJECT_ROOT"
              cd "$PROJECT_ROOT"
              git clone https://github.com/***Inc/Starteryou-Website.git -b develop Starteryou
            else
              log "Pulling latest changes..."
              cd "$REPO_DIR"
              git fetch origin develop
              git reset --hard origin/develop
            fi

            # Create the .env file
            log "Creating .env file..."
            rm -f "$ENV_FILE"
            touch "$ENV_FILE"
            chmod 600 "$ENV_FILE"

            cat > "$ENV_FILE" << EOF
            NODE_ENV=production
            MONGO_USER=${{ secrets.MONGO_USER }}
            MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}
            MONGO_HOST=localhost # Access via SSH tunnel
            MONGO_PORT=27017
            MONGO_DB=${{ secrets.MONGO_DB }}
            MONGO_AUTH_SOURCE=${{ secrets.MONGO_AUTH_SOURCE }}
            MONGO_TLS=true
            MONGO_TLS_CA=/etc/ssl/mongodb/ca.crt
            MONGO_TLS_CERT=/etc/ssl/mongodb/server.pem
            MONGO_APP_NAME=${{ secrets.MONGO_APP_NAME }}
            EOF

            # Restart Docker and clean up old resources
            log "Restarting Docker..."
            sudo systemctl start docker || sudo systemctl restart docker

            log "Cleaning up old Docker resources..."
            docker-compose down --volumes --remove-orphans
            docker system prune -af --volumes

            # Build and start containers
            log "Building and starting Docker containers..."
            docker-compose up -d --build

            log "Deployment completed successfully!"
