name: Deploy to AWS EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7  # Use a specific stable version
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e  # Stop execution on error
            cd /home/ec2-user/RevampUI/Starteryou
            git pull origin main

            # Ensure Docker is running
            sudo systemctl start docker || sudo systemctl restart docker

            # Bring down any existing containers and clean up resources
            docker-compose down --volumes --remove-orphans
            docker system prune -af --volumes

            # Rebuild and restart containers
            docker-compose up -d --build

            # Show Docker container status and logs
            docker ps
            docker logs starteryou-backend
            docker logs starteryou-frontend
