name: Deploy to AWS EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Fetch Certificates from DB Server
      - name: Fetch Certificates from DB Server
        env:
          DB_EC2_SSH_KEY: ${{ secrets.DB_EC2_SSH_KEY }}
          DB_EC2_HOST: ${{ secrets.DB_EC2_HOST }}
          DB_EC2_USER: ${{ secrets.DB_EC2_USER }}
        run: |
          set -e
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H $DB_EC2_HOST >> ~/.ssh/known_hosts
          echo "$DB_EC2_SSH_KEY" > ~/.ssh/db_key.pem
          chmod 600 ~/.ssh/db_key.pem

          echo "Fetching certificates from DB server..."
          ssh -i ~/.ssh/db_key.pem $DB_EC2_USER@$DB_EC2_HOST "sudo cat /etc/ssl/mongodb/ca.crt" > ./ca.crt
          ssh -i ~/.ssh/db_key.pem $DB_EC2_USER@$DB_EC2_HOST "sudo cat /etc/ssl/mongodb/server.pem" > ./server.pem


      # Step 3: Transfer Certificates to Target EC2 Server
      - name: Transfer Certificates to Target EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          set -e
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
          echo "$EC2_SSH_KEY" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem

          echo "Transferring certificates to EC2 server..."
          scp -i ~/.ssh/ec2_key.pem ./ca.crt $EC2_USER@$EC2_HOST:/tmp/ca.crt
          scp -i ~/.ssh/ec2_key.pem ./server.pem $EC2_USER@$EC2_HOST:/tmp/server.pem

      # Step 4: Deploy Application on Target EC2 Server
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.DB_EC2_SSH_KEY }}
          script: |
            set -e
            sudo mkdir -p /etc/ssl/mongodb
            sudo mv /tmp/ca.crt /etc/ssl/mongodb/ca.crt
            sudo mv /tmp/server.pem /etc/ssl/mongodb/server.pem
            sudo chmod 600 /etc/ssl/mongodb/*

            echo "Recreating Docker secrets..."
            docker secret rm mongo_tls_ca mongo_tls_cert || true
            docker secret create mongo_tls_ca /etc/ssl/mongodb/ca.crt
            docker secret create mongo_tls_cert /etc/ssl/mongodb/server.pem

            PROJECT_ROOT="/home/ec2-user/Starteryou-Website"
            REPO_DIR="${PROJECT_ROOT}/Starteryou"
            ENV_FILE="${REPO_DIR}/.env"

            mkdir -p "$PROJECT_ROOT"
            cd "$PROJECT_ROOT"

            if [ ! -d "$REPO_DIR" ]; then
              git clone https://github.com/starteryouInc/Starteryou-Website.git -b develop Starteryou
            else
              cd "$REPO_DIR"
              git fetch origin develop
              git reset --hard origin/develop
            fi

            echo "Generating .env file..."
            cat > "$ENV_FILE" << EOF
            NODE_ENV=production
            PORT=3000
            FRONTEND_URL=http://54.196.202.145:8080
            VITE_BACKEND_URL=http://54.196.202.145:3000
            MONGO_USER=${{ secrets.MONGO_USER }}
            MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}
            MONGO_HOST=localhost
            MONGO_PORT=27017
            MONGO_DB=${{ secrets.MONGO_DB }}
            MONGO_AUTH_SOURCE=${{ secrets.MONGO_AUTH_SOURCE }}
            MONGO_TLS=true
            MONGO_TLS_CA=/etc/ssl/mongodb/ca.crt
            MONGO_TLS_CERT=/etc/ssl/mongodb/server.pem
            MONGO_APP_NAME=${{ secrets.MONGO_APP_NAME }}
            EOF

            chmod 600 "$ENV_FILE"

            echo "Deploying Docker services..."
            docker-compose down --volumes --remove-orphans
            docker-compose up --build -d
