name: Deploy to AWS EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user # Make sure this matches your EC2 instance's username
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e  # Stop execution on error

            cd /home/ec2-user/Starteryou-Website/Starteryou
            git pull origin develop

            # Check if anything is using port 8080 and kill it
            if sudo lsof -i :8080; then
              sudo lsof -i :8080 | awk 'NR!=1 {print $2}' | xargs -r sudo kill -9
            fi

            # Remove old containers, volumes, and images
            docker-compose down --volumes --remove-orphans
            docker system prune -af --volumes

            # Restart containers
            docker-compose up -d --build

            # Show Docker container status and logs
            docker ps
            docker logs starteryou-backend
            docker logs starteryou-frontend

            # Check available disk space
            df -h
