name: Deploy to AWS EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user # Make sure this matches your EC2 instance's username
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/RevampUI/Starteryou
            git pull origin develop
            docker-compose down --remove-orphans  # This stops and removes all containers defined in docker-compose
            docker system prune -af  # This removes all unused containers, networks, images (both dangling and unreferenced), and optionally, volumes
            docker-compose up -d --build
            docker ps
            docker logs starteryou-backend
            docker logs starteryou-frontend
