name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Adjust to your Node.js version

    - name: Install dependencies
      working-directory: Starteryou # Update this if your path is different
      run: npm install

    - name: Build the app
      working-directory: Starteryou # Update this if your path is different
      run: npm run build

    - name: Prepare SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to AWS EC2 via SSH
      run: |
        ssh -v -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} << 'EOF'
          cd /path/to/your/project/on/ec2 # Navigate to the project directory on EC2

          # Clean up old Docker images and volumes
          docker system prune -a --volumes -f

          # Build the new Docker image
          docker build -t starteryou-ui-dev .

          # Stop and remove the old container if it's running
          docker stop starteryou-ui-dev-container || true
          docker rm starteryou-ui-dev-container || true

          # Run the new Docker image
          docker run -d -p 8080:8080 --name starteryou-ui-dev-container starteryou-ui-dev
        EOF
